require import AllCore Int List Distr.
require import BudgetParameters.
require import ParameterizedBudgetParameters.
require import SourceTypes.
require import ComparisonPayloadSemanticBridge.
require import ComparisonPayloadSemanticSlotMassParameterized.
import Ring.IntID StdOrder.IntOrder Range.

(* Parallel parameterized MS2 semantic bridge.
   This keeps the existing demo semantic bridge untouched and only adds a
   companion wrapper above the parameterized local mass owner. *)

lemma epsilon_ms_rom_programmability_semantic_eq_epsilon_ms_rom_programmability_parameterized :
  BudgetParameters.epsilon_ms_rom_programmability_semantic =
  ParameterizedBudgetParameters.epsilon_ms_rom_programmability_parameterized.
proof.
rewrite BudgetParameters.epsilon_ms_rom_programmability_semantic_closed_form.
rewrite ParameterizedBudgetParameters.epsilon_ms_rom_programmability_parameterized_closed_form.
rewrite /ParameterizedBudgetParameters.ms2_param_failure_count.
rewrite /ParameterizedBudgetParameters.ms2_param_total_count.
rewrite /ParameterizedBudgetParameters.ms2_param_global_digest_count.
rewrite /ParameterizedBudgetParameters.ms2_param_query_digest_count.
rewrite /ParameterizedBudgetParameters.ms2_param_transcript_count.
rewrite /ParameterizedBudgetParameters.ms2_param_clean_count.
by rewrite /BudgetParameters.ms_rom_failure_slot_count
  /BudgetParameters.ms_rom_total_slot_count.
qed.

lemma ms_rom_local_failure_mass_eq_parameterized :
  ms_rom_local_failure_mass = ms_rom_local_failure_mass_parameterized.
proof.
rewrite ms_rom_local_failure_mass_eq_epsilon_ms_rom_programmability_semantic.
rewrite ms_rom_local_failure_mass_eq_epsilon_ms_rom_programmability_parameterized.
exact epsilon_ms_rom_programmability_semantic_eq_epsilon_ms_rom_programmability_parameterized.
qed.

lemma ms_rom_execution_owned_semantic_failure_probability_eq_epsilon_ms_rom_programmability_parameterized
  (x : ms_public_input) :
  ms_rom_execution_owned_semantic_failure_probability x =
  ParameterizedBudgetParameters.epsilon_ms_rom_programmability_parameterized.
proof.
rewrite ms_rom_execution_owned_semantic_failure_probability_eq_local_mass.
rewrite ms_rom_local_failure_mass_eq_parameterized.
exact ms_rom_local_failure_mass_eq_epsilon_ms_rom_programmability_parameterized.
qed.

lemma A_MS2_rom_programming_execution_owned_parameterized_bound
  (x : ms_public_input) :
  ms_rom_execution_owned_semantic_failure_probability x <=
  ParameterizedBudgetParameters.epsilon_ms_rom_programmability_parameterized.
proof.
rewrite ms_rom_execution_owned_semantic_failure_probability_eq_local_mass.
rewrite ms_rom_local_failure_mass_eq_parameterized.
exact ms_rom_local_failure_mass_le_epsilon_ms_rom_programmability_parameterized.
qed.